### ISSUE TITLE
angular-faye is not being injected

### ISSUE THREAD

**Issue by driv** [monterail/angular-faye#3]
I've added angular-faye as a dependency to my proyect and installed bower, but the js file is not being injected.

The generated .bower.json file does not have a "main" property, so it does not know what to inject.
I've noticed there is a package.json file, but not a bower.json file. Why is that? From the comment of the commit 112635292b4edc246069345a9c93bb66d3c3717b I think that the project was converted to bower.

**Comment by karneaud** [comment]
tried to install via bower but got NOT FOUND. would be ice to get this in bower form
